signin:
  actif : on
  login:
    field: email
  bad_credentials:
    message: errors.login.bad_credentials
  path: /signin
  redirect: /
  template: devises/signin
  filter:
      actif: on
      session_key: id
      exceptions: []

signup:
  actif : on
  path: /signup
  redirect: /
  template: devises/signup
  login:
    not_empty:
      message: errors.messages.not_empty
    not_uniq:
      message: errors.messages.not_uniq
  password:
    field : password
    # if salf option is a field from form ( like email ), field's value will become the salt ( for uniq salt )
    salt: email
    hash : sha256
    confirm:
      field: cpassword
      message: errors.password.confirm
    regex:
      pattern: /^(?=.*\d)(?=.*[A-Z])[0-9A-Za-z]{8,}$/
      message: errors.password.regex
  table: users
  default:
    acl: user
  additional_fields: []

