# Routes

_home:
    path:   '/'
    controller:   'HelloController'
    action: 'run'
    method: 'GET'

_config:
    path: '/config'
    controller: 'ConfigController'
    action: 'config'

_logout:
    path: '/logout'
    controller: 'WalrusSigninController'
    action: 'logout'