errors:
  format: '%{attribute} %{message}'
  messages:
    required: is required
    not_required: is required
    empty: can't be empty
    equal_to: must be equal to %{count}
    even: must be even
    greater_than: must be greater than %{count}
    greater_than_or_equal_to: must be greater than or equal to %{count}
    invalid: is invalid
    number: is not a number
    integer: must be an integer
    odd: must be odd
    max:
      one: is too long (maximum is 1 character)
      other: is too long (maximum is %{count} characters)
    min:
      one: is too short (minimum is 1 character)
      other: is too short (minimum is %{count} characters)
    length:
      one: is the wrong length (should be 1 character)
      other: is the wrong length (should be %{count} characters)
