# Walrus Framework configuration

# RDBMS: mysql|SQLite|PostgreSQL|Oracle
RDBMS: "mysql"

# RDBMS host
host: "localhost"

# Database name
database: "walrus_dev"

# Database connexion user name
name: "root"

# Database connexion password
password: "root"

# Templating language: haml|smarty|php
templating: "smarty"

# Environment: dev|prod
environment: "dev"