# Routes

_home:
    path:   ''
    controller:   'HomeController'
    action: 'run'

_me:
    path: 'me'
    controller: 'UserController'
    action: 'run'

_sidebar_home:
    path: 'sidebar/home'
    controller: 'SidebarController'
    action: 'home'

_admin:
    path: 'admin'
    controller: 'HomeController'
    action: 'admin'
    acl: 'admin'

_config:
    path: 'config'
    controller: 'ConfigController'
    action: 'config'