# $this->map(
#     '/contact/',
#     array('controller' => 'someController', 'action' => 'contactAction'),
#     array('methods' => 'GET', 'name' => 'users_edit', 'filters' => array('id' => '(\d+)'))
# );

_home:
    path:   ''
    controller:   'HomeController'
    action: 'run'