# $this->map(
#     '/contact/',
#     array('controller' => 'someController', 'action' => 'contactAction'),
#     array('methods' => 'GET', 'name' => 'users_edit', 'filters' => array('id' => '(\d+)'))
# );

_hello:
    method: 'get'
    path:   'hello/:id'
    controller:   'HelloController'
    action: 'doHelloWorld'
    filters:
        require:
            id: '\d+'
        default:
            id: 1

_home:
    path:   ''
    controller:   'HelloController'
    action: 'helloHome'


_helloNew:
    path:   'helloNew'
    controller:   'HelloController'
    action: 'doHelloWorldNew'