# Routes

_home:
    path:   ''
    controller:   'HomeController'
    action: 'run'

_sidebar_home:
    path: 'sidebar/home'
    controller: 'SidebarController'
    action: 'home'

_config:
    path: 'config'
    controller: 'ConfigController'
    action: 'config'