_home:
    path:   ''
    controller:   'HelloController'
    action: 'helloHome'

_hello:
    method: 'get'
    path:   '/hello/:id'
    controller:   'HelloController'
    action: 'doHelloWorld'
    params:
        require:
            id: '\d+'
        default:
            id: 1

_helloNew:
    path:   '/helloNew'
    controller:   'HelloController'
    action: 'doHelloWorldNew'