# skeleton_name:
#     header:
#         template: "module/template"
#     body:
#         template: "module/template"
#     footer:
#         template: "module/template"

# Skeleton for connexion / inscription
_skeleton_home:
    header:
        template: 'header/main'
    nav:
        template: 'nav/main'
    body:
        template: 'home/form'
    footer:
        template: 'footer/main'

# Skeleton for dashboard
_skeleton_main:
    header:
        template: 'header/main'
    nav:
        template: 'nav/main'
    user:
        template: 'user/bar'
    body:
        template: 'actu/home'
    footer:
        template: 'footer/main'