# Form exemple

# _form_login:
#   form:
#     method: POST
#     action: /my-form
#     submit: Send
#     structure: list
#
#   fields:
#     email:
#       type: text
#       required: true
#       label: Your email
#       validate: /^\w{3,10}$/
#     password:
#       type: password
#       required: true
#       id: helloworld
#     sexe:
#       type: radio
#       required: true
#       options:
#         male:
#           label: Male
#         female:
#           label: Female
#     newsletter:
#       type: checkbox
#       options:
#         1:
#           label: 'Yes'
#         0:
#           label: 'No'
#       validate:
#         - 0
#         - 1
#     categories:
#       type: select
#       function: HelloController::getSelect
#       required: true
#     transport:
#       type: select
#       options:
#         - train
#         - voiture
#         - jambes

